# Generated by Django 3.0.10 on 2021-11-12 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del cargo')),
                ('nivel_subordinacion', models.CharField(choices=[('', '--------'), ('OC', 'Oficina Central'), ('P', 'Provincial'), ('M', 'Municipal')], max_length=50, verbose_name='Nivel de subordinacion')),
                ('vacante', models.BooleanField(default=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='clasificadorDPA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True, verbose_name='Codigo')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Clasificador_DPA',
                'verbose_name_plural': 'Clasificador_DPA',
                'db_table': 'Clasificador_DPA',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre de la especialidad')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'db_table': 'Especialidad',
            },
        ),
        migrations.CreateModel(
            name='Cuadro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('', '--------'), ('DS', 'Directivo Superior'), ('DI', 'Directivo Intermedio'), ('E', 'Ejecutivo')], max_length=200, verbose_name='Categoria')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('ci', models.IntegerField(unique=True, verbose_name='Carnet de Identidad')),
                ('anos_experiencia_direccion', models.PositiveIntegerField(blank=True, null=True, verbose_name='Años de experiencia Direccion')),
                ('anos_experiencia_rama', models.PositiveIntegerField(blank=True, null=True, verbose_name='Años de experiencia Rama')),
                ('militancia', models.CharField(blank=True, choices=[('', '--------'), ('PCC', 'PCC'), ('UJC', 'UJC')], max_length=50, null=True, verbose_name='Militancia')),
                ('sexo', models.CharField(choices=[('', '--------'), ('F', 'Femenino'), ('M', 'Masculino')], max_length=50, verbose_name='Sexo')),
                ('color', models.CharField(choices=[('', '--------'), ('B', 'Blanca'), ('M', 'Mulata'), ('N', 'Negra')], max_length=50, verbose_name='Color')),
                ('edad', models.PositiveIntegerField(verbose_name='Edad')),
                ('fk_cargo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuadro.Cargo', verbose_name='Cargo')),
                ('fk_especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuadro.Especialidad', verbose_name='Especialidad')),
            ],
            options={
                'verbose_name': 'Cuadro',
                'verbose_name_plural': 'Cuadros',
                'db_table': 'Cuadros',
            },
        ),
        migrations.AddField(
            model_name='cargo',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='municipio', to='cuadro.clasificadorDPA', verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provincia', to='cuadro.clasificadorDPA', verbose_name='Provincia'),
        ),
    ]
