# Generated by Django 3.0.10 on 2021-11-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadro',
            name='ci',
            field=models.BigIntegerField(unique=True, verbose_name='Carnet de Identidad'),
        ),
    ]
