# Generated by Django 3.0.10 on 2021-11-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadro', '0003_cuadro_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadro',
            name='ci',
            field=models.BigIntegerField(verbose_name='Carnet de Identidad'),
        ),
    ]
