# Generated by Django 3.0.10 on 2021-11-24 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuadro', '0004_auto_20211118_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadro',
            name='fk_cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuadro.Cargo', verbose_name='Cargo'),
        ),
    ]
