# Generated by Django 3.0.10 on 2021-11-30 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuadro', '0005_auto_20211124_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificadorCargoCuadro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True, verbose_name='Codigo')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Clasificador_Cargo_Cuadro',
                'verbose_name_plural': 'Clasificador_Cargos_Cuadros',
                'db_table': 'Clasificador_Cargo_Cuadro',
                'ordering': ['codigo'],
            },
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='nombre',
        ),
        migrations.AddField(
            model_name='cargo',
            name='fk_clasificador_cargo_cuadro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuadro.ClasificadorCargoCuadro', verbose_name='Nombre del Cargo'),
        ),
    ]
