# Generated by Django 3.0.10 on 2022-01-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadro', '0007_auto_20211203_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='observaciones',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='cuadro',
            name='categoria_cientifica',
            field=models.CharField(blank=True, choices=[('', '--------'), ('L', 'Licenciado'), ('I', 'Ingeniero'), ('D', 'Doctor'), ('M', 'Máster')], max_length=20, null=True, verbose_name='Categoria Cientifica'),
        ),
        migrations.AddField(
            model_name='cuadro',
            name='escolaridad',
            field=models.CharField(blank=True, choices=[('', '--------'), ('SE', 'Segundario'), ('TM', 'Tecnico Medio'), ('MS', 'Medio Superio'), ('SU', 'Superior')], max_length=20, null=True, verbose_name='Escolaridad'),
        ),
        migrations.AddField(
            model_name='cuadro',
            name='observaciones',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='nivel_subordinacion',
            field=models.CharField(choices=[('', '--------'), ('OC', 'Oficina Central'), ('UAS', 'Unidad de Aseguramiento y Servicios'), ('P', 'Provincial'), ('M', 'Municipal')], max_length=50, verbose_name='Nivel de subordinacion'),
        ),
        migrations.AlterField(
            model_name='cuadro',
            name='categoria',
            field=models.CharField(choices=[('', '--------'), ('DS', 'Directivo Superior'), ('DI', 'Directivo Intermedio'), ('E', 'Ejecutivo')], max_length=50, verbose_name='Categoria'),
        ),
    ]
