# Generated by Django 3.0.10 on 2022-01-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadro', '0010_auto_20220110_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadro',
            name='fecha_alta',
            field=models.DateField(verbose_name='Fecha de Alta'),
        ),
        migrations.AlterField(
            model_name='cuadro',
            name='fecha_baja',
            field=models.DateField(verbose_name='Fecha de Baja'),
        ),
    ]
