# Generated by Django 3.0.10 on 2022-01-10 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuadro', '0011_auto_20220110_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuadro',
            name='fk_movimiento',
        ),
        migrations.DeleteModel(
            name='Movimiento',
        ),
    ]
