# Generated by Django 3.0.10 on 2022-01-10 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuadro', '0012_auto_20220110_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True, verbose_name='Codigo')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'db_table': 'Movimiento',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='cuadro',
            name='fk_movimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuadro.Movimiento', verbose_name='Movimiento'),
        ),
    ]
