# Generated by Django 3.0.10 on 2022-01-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadro', '0015_auto_20220113_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialidad',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='especialidad',
            name='nombre',
        ),
        migrations.AddField(
            model_name='especialidad',
            name='codigo',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='Codigo'),
        ),
        migrations.AddField(
            model_name='especialidad',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='especialidad',
            name='nivel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nivel Escolar'),
        ),
        migrations.AlterField(
            model_name='cuadro',
            name='escolaridad',
            field=models.CharField(blank=True, choices=[('', '--------'), ('9noGrado', '9no Grado'), ('12moGrado', '12mo Grado'), ('Tec.Med.', 'Tecnico Medio'), ('Universitario', 'Universitario')], max_length=20, null=True, verbose_name='Escolaridad'),
        ),
    ]
