# Generated by Django 3.0.10 on 2022-01-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadro', '0016_auto_20220119_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModalidadPromocion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True, verbose_name='Codigo')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Modalidad Promocion',
                'verbose_name_plural': 'Modalidad Promocion',
                'db_table': 'Modalidad Promocion',
                'ordering': ['codigo'],
            },
        ),
        migrations.AlterField(
            model_name='cuadro',
            name='escolaridad',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Escolaridad'),
        ),
        migrations.RemoveField(
            model_name='cuadro',
            name='modalidad_promocion',
        ),
        migrations.AddField(
            model_name='cuadro',
            name='modalidad_promocion',
            field=models.ManyToManyField(blank=True, null=True, to='cuadro.ModalidadPromocion', verbose_name='Modalidad del movimiento por Promocion'),
        ),
    ]
